[[Bricks]]
ID      = "light"
Shape   = "any"
Tags    = [
    "entity",
    "light",
    "metal",
    "glass",
    "decoration",
    "buildable",
    "convertable_truss",
]
[Bricks.Textures]
Connected = true
Default   = ["light.0"]
