[[Bricks]]
ID      = "thruster"
Shape   = "custom"
Mesh    = "thruster.obj"
Tags    = [
    "entity",
    "metal",
    "thruster",
    "buildable",
    "orientable",
    "convertable_truss",
]
[Bricks.Textures]
Default = ["vent"]
