"Language" = "en"

[Translations]
"item.base.caution_panel" = "Caution Panel"
"item.base.display_console" = "Console"
"item.base.display_control" = "Display"
"item.base.display_monitor" = "Computer"
"item.base.glass" = "Glass"
"item.base.ice" = "Ice"
"item.base.laser" = "Mining Laser"
"item.base.light" = "Light"
"item.base.panel" = "Panel"
"item.base.rock" = "Rock"
"item.base.small_light" = "Small Light"
"item.base.storage" = "Storage Unit"
"item.base.thruster" = "Thruster"
"item.base.truss" = "Truss"
"item.base.control_buttons" = "Button Panel"
"item.base.grate" = "Grate"
"item.base.core" = "Core"
"item.base.porthole" = "Porthole"
"item.base.vent" = "Vent"
"item.base.control_panel" = "Control Panel"
