"Language" = "en"

[Translations]
"notification.save.creating" = "Creating \"{0}\"..."
"notification.save.created" = "Created save \"{0}\"."
"notification.save.loading" = "Loading \"{0}\"..."
"notification.save.loaded" = "Loaded save \"{0}\"."
"notification.save.saving" = "Saving \"{0}\"..."
"notification.save.saved" = "Saved \"{0}\"."
"notification.save.saving.failed" = "Save failed, some information may be lost."

"ui.notification.saveNameEmpty" = "Name required"
"ui.notification.saveNameTaken" = "Name taken"
"ui.notification.tooSoon" = "Please wait a few moments"
