"Language" = "en"

[Translations]
"ui.button.back" = "Back"

"ui.button.singleplayer" = "Singleplayer"
"ui.button.multiplayer" = "Multiplayer"
"ui.button.settings" = "Settings"
"ui.button.quit" = "Quit game"

"ui.button.continue" = "Continue game"
"ui.button.saveAndExit" = "Save & exit"

"ui.menu.createSave" = "Create Save"
"ui.menu.saves" = "Game Saves"
"ui.button.newGame" = "+ Begin journey"
"ui.field.saveName" = "Enter save name..."
"ui.field.saveSeed" = "[Random]"

"ui.menu.display" = "Display"
"ui.setting.vsync" = "VSync"
"ui.setting.fullscreen" = "Fullscreen"
"ui.setting.msaa" = "Anti-aliasing"
"ui.setting.fov" = "Field of view"

"ui.menu.controls" = "Controls"
"ui.setting.mouseSensitivity" = "Sensitivity"

"ui.menu.volume" = "Volume"
"ui.setting.volume.master" = "Master"
"ui.setting.volume.interface" = "Interface"
"ui.setting.volume.effects" = "Effects"

"ui.hint.changeShape" = "R: Change shape"
"ui.hint.changeOrientation" = "T: Change orientation"
"ui.hint.snapBrick" = "Shift: Snap brick"
"ui.hint.pickBrick" = "MMB: Pick brick"
"ui.hint.breakBrick" = "LMB: Break brick"
"ui.hint.placeBrick" = "RMB: Place brick"
"ui.hint.movement.roll" = "Q/E: Roll"
"ui.hint.movement.up" = "Space: Up"
"ui.hint.movement.down" = "Ctrl: Down"
"ui.hint.movement" = "W/A/S/D: Fly"
"ui.hint.quit" = "Esc: Pause"
"ui.hint.quicksave" = "F5: Quicksave"
"ui.hint.inventory" = "Tab: Inventory"
