[[Items]]
ID       = "caution_panel"
Name     = "item.base.caution_panel"
Icon     = "block/caution_panel.png"
MaxStack = 100
[Items.Placeable]
Type     = "brick"
ID       = "caution_panel"
[Items.ViewModel]
Mesh       = "cube.obj"
Material   = "bricks/caution_panel"
Position.X = 0.4
Position.Y = -0.4
Position.Z = -0.5
Rotation.X = 0
Rotation.Y = 30
Rotation.Z = 0
Scale.X    = 0.25
Scale.Y    = 0.25
Scale.Z    = 0.25
[Items.WorldModel]
Mesh       = "cube.obj"
Material   = "bricks/caution_panel"