[[Items]]
ID       = "control_buttons"
Name     = "item.base.control_buttons"
Icon     = "block/control_buttons.0.png"
MaxStack = 100
[Items.Placeable]
Type     = "brick"
ID       = "control_buttons"
[Items.ViewModel]
Mesh       = "cube.obj"
Material   = "bricks/control_buttons"
Position.X = 0.4
Position.Y = -0.4
Position.Z = -0.5
Rotation.X = 0
Rotation.Y = 30
Rotation.Z = 0
Scale.X    = 0.25
Scale.Y    = 0.25
Scale.Z    = 0.25
[Items.WorldModel]
Mesh       = "cube.obj"
Material   = "bricks/control_buttons"