[[Items]]
ID       = "display_console"
Name     = "item.base.display_console"
Icon     = "block/display_console.png"
MaxStack = 100
[Items.Placeable]
Type     = "brick"
ID       = "display_console"
[Items.ViewModel]
Mesh       = "cube.obj"
Material   = "bricks/display_console"
Position.X = 0.4
Position.Y = -0.4
Position.Z = -0.5
Rotation.X = 0
Rotation.Y = 30
Rotation.Z = 0
Scale.X    = 0.25
Scale.Y    = 0.25
Scale.Z    = 0.25
[Items.WorldModel]
Mesh       = "cube.obj"
Material   = "bricks/display_console"