[[Items]]
ID              = "drill"
Name            = "item.base.drill"
Icon            = "items/drill.png"
MaxStack        = 1
[Items.Tool]
Type            = "convert"
Target          = "truss"
Tags = [
    "convertable_truss",
]