[[Items]]
ID         = "laser"
Name       = "item.base.laser"
Icon       = "items/laser.png"
MaxStack   = 1
[Items.Tool]
Type       = "mining"
[Items.ViewModel]
Mesh       = "items/laser.obj"
Material   = "items/laser"
Position.X = 0.5
Position.Y = -0.4
Position.Z = 0.2
Rotation.X = 0
Rotation.Y = 5
Rotation.Z = 0
[Items.WorldModel]
Mesh       = "items/laser.obj"
Material   = "items/laser"